/**
 * WireScript DSL (.ws) Import / Export Tests
 *
 * Covers:
 *  - exportWs: DB → .ws string
 *  - importWs: .ws string → DB
 *  - dbToWs / wsToDb aliases
 *  - validation (module syntax rejection)
 *  - round-trip: DSL → DB → .ws → DB
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { Component } from '../core/Component';
import { Pin } from '../core/Pin';
import { Node } from '../core/Node';
import { Circuit, DC, GND, R, C, L, NPN } from '../core';
import { compileDslToDb } from '../core/db';
import { exportWs, importWs, dbToWs, wsToDb } from '../core/ws';

beforeEach(() => {
  Component.resetCounter();
  Pin.resetCounter();
  Node.resetCounter();
});

// ─────────────────────────────────────────────────────────────────────────────
// exportWs — DB → .ws
// ─────────────────────────────────────────────────────────────────────────────

describe('exportWs — DB → .ws', () => {
  it('produces a string containing Circuit()', () => {
    const circuit = Circuit('LED Driver', DC(5), R(330), GND());
    const db = compileDslToDb(circuit);
    const ws = exportWs(db);

    expect(typeof ws).toBe('string');
    expect(ws).toContain('Circuit(');
    expect(ws).toContain('"LED Driver"');
  });

  it('contains component variable declarations', () => {
    const circuit = Circuit('RC', DC(5), R(1000), C(1e-6), GND());
    const db = compileDslToDb(circuit);
    const ws = exportWs(db);

    expect(ws).toContain('= DC(');
    expect(ws).toContain('= R(');
    expect(ws).toContain('= C(');
    expect(ws).toContain('= GND(');
  });

  it('contains pin connection paths', () => {
    const circuit = Circuit('Simple', DC(5), R(1000), GND());
    const db = compileDslToDb(circuit);
    const ws = exportWs(db);

    expect(ws).toContain('.p');
    expect(ws).toContain('.p1');
    expect(ws).toContain('.p2');
  });

  it('does NOT contain import/export statements', () => {
    const circuit = Circuit('Clean', DC(5), R(100), GND());
    const db = compileDslToDb(circuit);
    const ws = exportWs(db);

    expect(ws).not.toMatch(/\bimport\b/);
    expect(ws).not.toMatch(/\bexport\b/);
    expect(ws).not.toContain('require(');
  });

  it('appends header comments when provided', () => {
    const circuit = Circuit('Commented', DC(3.3), R(470), GND());
    const db = compileDslToDb(circuit);
    const ws = exportWs(db, {
      header: ['Auto-generated by WireScript Studio', 'Project: My PCB'],
    });

    expect(ws).toContain('// Auto-generated by WireScript Studio');
    expect(ws).toContain('// Project: My PCB');
  });

  it('uses dbToWs alias correctly', () => {
    const circuit = Circuit('Alias', DC(5), R(100), GND());
    const db = compileDslToDb(circuit);
    const ws = dbToWs(db);
    expect(ws).toContain('Circuit(');
  });

  it('handles BJT circuits', () => {
    const t = NPN('2N2222');
    const circuit = Circuit('Switch', [
      [DC(5), R(1000), t.C],
      [t.E, GND()],
      [DC(5), R(10000), t.B],
    ]);
    const db = compileDslToDb(circuit);
    const ws = exportWs(db);

    expect(ws).toContain('NPN(');
    expect(ws).toContain('Circuit(');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// importWs — .ws → DB
// ─────────────────────────────────────────────────────────────────────────────

describe('importWs — .ws → DB', () => {
  it('parses a simple .ws string', () => {
    const ws = `
V1 = DC(5)
R1 = R(1000)
GND1 = GND()

Circuit(
  "RC Test",
  [
    [V1.p, R1.p1],
    [V1.n, R1.p2, GND1.gnd]
  ]
)`;

    const db = importWs(ws);
    expect(db.schema).toBe('wirescript-db@v1');
    expect(db.name).toBe('RC Test');
    expect(db.components.length).toBe(3);
    expect(db.nodes.length).toBeGreaterThan(0);
  });

  it('uses wsToDb alias correctly', () => {
    const ws = `
V1 = DC(5)
R1 = R(100)
GND1 = GND()
Circuit("Alias Test", [
  [V1.p, R1.p1],
  [V1.n, R1.p2, GND1.gnd]
])`;

    const db = wsToDb(ws);
    expect(db.components.length).toBe(3);
  });

  it('throws when source contains import statements', () => {
    const bad = `
import { R } from 'wirescript';
Circuit("Bad", [])`;

    expect(() => importWs(bad)).toThrow('.ws files must not contain');
  });

  it('throws when source contains export statements', () => {
    const bad = `
export default Circuit("Bad", [])`;

    expect(() => importWs(bad)).toThrow('.ws files must not contain');
  });

  it('throws when source has no Circuit() call', () => {
    const bad = `V1 = DC(5)\nR1 = R(100)`;
    expect(() => importWs(bad)).toThrow('Circuit(...)');
  });

  it('respects the name override option', () => {
    const ws = `
V1 = DC(5)
R1 = R(100)
GND1 = GND()
Circuit("Original Name", [
  [V1.p, R1.p1],
  [V1.n, R1.p2, GND1.gnd]
])`;

    const db = importWs(ws, { name: 'Overridden Name' });
    expect(db.name).toBe('Overridden Name');
  });

  it('imports a component-rich circuit', () => {
    const ws = `
V1 = DC(5)
R1 = R(330)
C1 = C(0.000001)
L1 = L(0.001)
GND1 = GND()

Circuit(
  "Rich",
  [
    [V1.p, R1.p1],
    [R1.p2, C1.p1, L1.p1],
    [C1.p2, V1.n, GND1.gnd],
    [L1.p2, GND1.gnd]
  ]
)`;

    const db = importWs(ws);
    expect(db.components.length).toBe(5);
    expect(db.components.some(c => c.type === 'resistor')).toBe(true);
    expect(db.components.some(c => c.type === 'capacitor')).toBe(true);
    expect(db.components.some(c => c.type === 'inductor')).toBe(true);
  });

  it('all connected pins have valid nodeIds', () => {
    const ws = `
V1 = DC(5)
R1 = R(1000)
GND1 = GND()
Circuit("Conn", [
  [V1.p, R1.p1],
  [V1.n, R1.p2, GND1.gnd]
])`;

    const db = importWs(ws);
    const nodeIds = new Set(db.nodes.map(n => n.id));
    for (const comp of db.components) {
      for (const pin of comp.pins) {
        if (pin.nodeId) {
          expect(nodeIds.has(pin.nodeId)).toBe(true);
        }
      }
    }
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Round-trip: DSL → DB → .ws → DB
// ─────────────────────────────────────────────────────────────────────────────

describe('.ws round-trip', () => {
  it('DSL → DB → .ws → DB preserves component count', () => {
    const circuit = Circuit('RT', DC(5), R(1000), C(1e-6), GND());
    const original = compileDslToDb(circuit);

    const ws = exportWs(original);
    const rebuilt = importWs(ws);

    expect(rebuilt.components.length).toBe(original.components.length);
  });

  it('DSL → DB → .ws → DB preserves schematic name', () => {
    const circuit = Circuit('My Named Circuit', DC(3.3), R(220), GND());
    const original = compileDslToDb(circuit);

    const ws = exportWs(original);
    const rebuilt = importWs(ws);

    expect(rebuilt.name).toBe(original.name);
  });

  it('DSL → DB → .ws → DB preserves connectivity', () => {
    const circuit = Circuit('ConnRT', DC(5), R(1000), GND());
    const original = compileDslToDb(circuit);

    const ws = exportWs(original);
    const rebuilt = importWs(ws);

    const connectedPins = rebuilt.components
      .flatMap(c => c.pins)
      .filter(p => p.nodeId);

    expect(connectedPins.length).toBeGreaterThan(0);
    const nodeIds = new Set(rebuilt.nodes.map(n => n.id));
    for (const pin of connectedPins) {
      expect(nodeIds.has(pin.nodeId!)).toBe(true);
    }
  });

  it('exported .ws is re-executable (no module syntax)', () => {
    const circuit = Circuit('Exec', DC(5), R(470), GND());
    const db = compileDslToDb(circuit);
    const ws = exportWs(db);

    // Verify no module syntax leaked in
    expect(ws).not.toMatch(/\bimport\b/);
    expect(ws).not.toMatch(/\bexport\b/);

    // Should be parseable
    const rebuilt = importWs(ws);
    expect(rebuilt.components.length).toBe(db.components.length);
  });

  it('triple round-trip stays stable', () => {
    const circuit = Circuit('Triple', DC(5), R(1000), GND());
    const db1 = compileDslToDb(circuit);

    const ws1 = exportWs(db1);
    const db2 = importWs(ws1);
    const ws2 = exportWs(db2);
    const db3 = importWs(ws2);

    expect(db3.components.length).toBe(db1.components.length);
    expect(db3.name).toBe(db1.name);
  });
});
